### ISSUE TITLE
Give support for RAML 1.0

### ISSUE THREAD

**Issue by HugoRuiz** [raml2html/raml2html#156]
Is there a milestone in the roadmap to support RAML 1.0?
Types and Examples are key improvements that would be very nice to have.

**Comment by kevinrenskers** [comment]
No, please see #153 as to why there won't be new features.

**Comment by oberlies** [comment]
We got raml2html work with RAML 1.0 file by disabling the validation. All you have to do for this is to change the `raml.loadFile(source)` in raml2obj to `raml.loadFile(source, {validate: false})`.

Note that this means that you would be still using the 0.8 parser. I scrapped my attempts to make raml2obj to use the 1.0 parser - this turned out to be pretty difficult because the new parser produces a different object (cf. https://github.com/raml-org/raml-js-parser-2/issues/11)

If you are interested in this, check out our fork at https://github.com/type-raml/raml2obj

**Comment by zypo** [comment]
Thanks @oberlies , that did the job for now!

**Comment by mikestowe** [comment]
This is now in progress...

**Comment by lazutkin** [comment]
@mikestowe :clap:  really nice to hear

**Comment by DataGreed** [comment]
Awesome!

**Comment by sebastianhenneberg** [comment]
Great, can't wait for it to arrive.

**Comment by thijsterlouw** [comment]
+1 for RAML 1.0 support, thanks!

**Comment by kulak-at** [comment]
+1 For RAML1.0 support, that would be great.

**Comment by supertylerc** [comment]
:+1:

**Comment by fuentecilla86** [comment]
+1

**Comment by danieslo** [comment]
+1

**Comment by veselov** [comment]
+1

**Comment by surfeurX** [comment]
+1

**Comment by stegmai** [comment]
+1

**Comment by kevinrenskers** [comment]
Adding +1's won't make it any faster, submitting PR's and/or helping @mikestowe will :) 

If you just want to be notified on changes, you can use the Subscribe button to the right. Please don't add +1 comments, as everyone will get an email. Kinda annoying.

**Comment by mathiasmoeller** [comment]
+1

**Comment by itrufeng** [comment]
+1 for RAML1.0 support, :+1:

**Comment by sichvoge** [comment]
There is an experimental branch `raml1.0` and a PR waiting to get merged that adds the 1.0 support.

**Comment by mikestowe** [comment]
Branch merged in - would love for people to test it out, submit bugs, contribute. Thanks!!!

**Comment by kevinrenskers** [comment]
#254
