### ISSUE TITLE
write errors on STDERR

### ISSUE THREAD

**Issue by allan-simon** [raml2html/raml2html#163]
in our CI system, we have a job that check if our RAML are correct by trying to run raml2html on it, the problem is when everything is correct, it output the html, which kind of polluate the CI logs

with most of commands it's solved by  doing  `command > /dev/null` as then only the STDERR will be printed out

so if raml2html can be updated to follow this standard it would improve the integration of this tool, thanks

**Comment by kevinrenskers** [comment]
Why not use the official https://github.com/raml-org/raml-js-parser for validation? Seems to make more sense then to use raml2html for that.

Otherwise try to use raml2html as a library instead of running it from the command line. If you do have to run it from the command line, use the `-o` option so HTML won't be written to the console. Sadly that means errors are also written to the HTML file but the process will exit with code 1 so you can check for that at least. In general the exit code is better for pure validation.

**Comment by allan-simon** [comment]
yup currently it's what i've done as a workaround  `raml2html -o /tmp/not_used` 

raml-js-parser being a javascript library, it's kind a hard to integrate with non-js stack.

so after we could develop a tool that use raml-js-parser , but it would add too much development overhead.

**Comment by kevinrenskers** [comment]
You can call javascript code via node, as a command line script just like raml2html.

But yeah I'd use the process exit code to check for validation. The next version of raml2html will write error to stderr, for now it's just to stdout.

**Comment by kevinrenskers** [comment]
2.2.0 has been released

**Comment by allan-simon** [comment]
thanks a lot
