### ISSUE TITLE
Add support for Security Scopes

### ISSUE THREAD

**Issue by nmors** [raml2html/raml2html#165]
Please also add support for scopes, e.g.
```
/users/{userid}/gists:
    get:
        securedBy: [oauth_2_0: { scopes: [ ADMINISTRATOR ] } ]
```

I think it is important to show who can actually access the endpoint / method. E.g. 

Secured by: oauth_2_0
Accessible by: ADMINISTRATOR

Related to:
#160 
#162 

Thanks!

**Comment by kevinduffey** [comment]
Definitely agree on this. There needs to be a good way to identify what scope can access an API, and I would even go as far as an option to generate docs for a given scope(s), so that you could separate documentation for different scopes if you want. I dont know if many/any documented APIs do this, but I would imagine it may be possible the creators of an API with "hidden" API endpoints, either because they are for admin only, or perhaps they are for use by their own UI only (not exactly a good idea, but many APIs are built this way today). I would imagine with the capability to optionally generate documentation based on scope level, API producers could have Admin doc accessible for only those that have admin rights and not visible by those without.

**Comment by nmors** [comment]
Interesting!

I didn't think of also having the ability to actually generate the doc based on a given scope. I like it!

**Comment by nmors** [comment]
relates to #10

**Comment by nmors** [comment]
I'm going to take a stab at implementing this, hopefully you will get a PR soon
