### ISSUE TITLE
Blank name for response headers

### ISSUE THREAD

**Issue by andrewcurioso** [raml2html/raml2html#287]
If you specify a responses header the resulting HTML has a blank name. Example RAML:

```raml
#%RAML 1.0

title: My Test API

/test:
  get:
    responses:
      200:
        headers:
          Content-Type:
            type: string
            description: "The type of content being returned"
```

Produces:
![screen shot 2016-12-07 at 3 17 27 pm](https://cloud.githubusercontent.com/assets/587738/20984934/444d3ef0-bc90-11e6-9627-f777701f3ce3.png)

**Comment by kevinrenskers** [comment]
Hey, thanks for the report. Did you try to fix the problem in the template? Or is it a problem with the actual data maybe?  Your help would be greatly appreciated, thanks! :)

**Comment by andrewcurioso** [comment]
@kevinrenskers The RAML is correct as far as I can tell. I tried directly with the example from the RAML spec document and it has the same bug:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#responses

Request headers work fine. It is just the response headers that don't.

**Comment by nickwb** [comment]
Hi @kevinrenskers and @andrewcurioso.

This is a +1 from me. The issue seems to be that `raml2obj` does not emit a `key` property for response headers.

Based on a really quick scan of `raml2obj`, this seems to be because [This line](https://github.com/raml2html/raml2obj/blob/master/arrays-objects-helpers.js#L53) does not recurse in to the `200`, `500`, etc. status codes - and therefore the headers object below them are not mapped in to the necessary array format.

**Comment by nickwb** [comment]
Hello again.

I have a workaround/fix for this issue which may assist. I'm not sure if this is the best way to fix the problem, but it certainly works.

I've added the following to `raml2obj/consistency-helpers.js`.

Under `makeConsistent`, I've added the following additional check:

```js
	if(!obj.key && obj.name) {
		obj.key = obj.name;
	}
```

Regards,
Nick
