### ISSUE TITLE
Looking for more awesome people to contribute

### ISSUE THREAD

**Issue by sichvoge** [raml2html/raml2html#308]
raml2html is one of the most successful RAML projects with over 24k downloads in the last month. With the latest changes, supporting RAML 1.0, we are currently looking for awesome people that help us to maintain and keep it as successful as it is.

Kevin, the brain behind this project, will move on to tackle other projects. Hence, it’s your time to jump in and lift his baby to the next stage.

Please let us know if you’d like to help and support by commenting down on this issue. If not, but maybe you know someone, tweet - get out the word that we are looking for contributors. 

Contributors should do either one or all (is up to you and your time):

- Review and answer issues
- Review open PRs and merge
- Code Code Code

Help us to keep this amazing project alive and well.

What about you @MichaelIT or @naterkane ;)

**Comment by MichaelIT** [comment]
why not.😊

**Comment by nickburns2006** [comment]
I'm in if you need some help.

**Comment by kevinrenskers** [comment]
The best way to get started is simply by picking up open issues in raml2obj and raml2html. Fix some bugs, add missing features, send pull requests, help to answer questions. After that we can give you push access to the repos.

**Comment by sichvoge** [comment]
Thans @nickburns2006 and @MichaelIT. Looking forward to your contribution!!!

**Comment by psychoo118** [comment]
I would be happy to help here too :)

**Comment by sichvoge** [comment]
Super awesome! You can start reviewing issues and where you can help!

**Comment by psychoo118** [comment]
already have 3 PRs :) looking for more to do in the evening.

**Comment by sichvoge** [comment]
Super cool! @MichaelIT you're welcome to review. Meanwhile, @kevinrenskers will continue for some time I guess :P

**Comment by it-sumanp** [comment]
Hey Its super .. I want to contribute to this project ..

**Comment by kevinrenskers** [comment]
Awesome! The best way to get started is simply by picking up open issues in [raml2obj](https://github.com/raml2html/raml2obj) and raml2html. Fix some bugs, add missing features, send pull requests, help to answer questions. After that we can give you push access to the repos.

**Comment by kevinrenskers** [comment]
At everyone who wants to contribute: there are currently 2 open PR's in raml2html and raml2html-default-theme, which could use some proper testing before we release it to NPM. @psychoo118, @MichaelIT, @nickburns2006, @it-sumanp, this shouldn't be too hard.

In short:
https://github.com/raml2html/raml2html/pull/334 is for updating raml2html to use the newest version of raml2obj. It has backwards incompatible changes to the securedBy stuff, so that's why the default template needs to be updated as well. Et voila: https://github.com/raml2html/default-theme/pull/2. Together this should be enough to deal with the new raml2obj and fix some other bugs in the process. We just need to make sure that everything still works as expected and since we don't have unit tests for the theme output, we need to do this by hand.

If someone wants to contribute with some basic unit tests for the default theme, that'd be very awesome as well :)

**Comment by kevinrenskers** [comment]
If you want to test these new versions, make sure you checkout the develop branch of both repo's and then 

1. Checkout raml2html-default-theme, open folder, `npm link`.
2. Checkout raml2html, open folder. First `npm link raml2html-default-theme` and then `npm link`.

Now both projects are installed globally, but using the local development versions of both. From the theme repo's example folder you can run the `render-all-examples` script without problem.

**Comment by MichaelIT** [comment]
hi, @kevinrenskers. I just check all html file after run `render-all-examples` script. it look`s good, but I found a problem in sub example node. It seem the first word in example was separated.

![qq20170320-220429](https://cloud.githubusercontent.com/assets/5445733/24103108/35d2bd9e-0db9-11e7-9821-aedda2a7e9dc.png)

**Comment by kevinrenskers** [comment]
Looks like the example is recognized as "nginx", causing this syntax highlighting.

**Comment by kevinrenskers** [comment]
Hey guys! There are currently 28 open issues between raml2html and raml2obj, so if someone has free time and wants to improve these projects, now is really a perfect time to jump in :) 

https://github.com/raml2html/raml2obj/issues/38 would be a great one to get started with. It's about using the new `load` function from raml-js-parser-2, which has an improved output so raml2obj doesn't need to do so much work anymore to get a useable format to raml2html. We have unit tests in place to make sure we stick to the same output, so that should help a lot.

Then we should really tackle the open issues related to inheritance:

- https://github.com/raml2html/raml2obj/issues/34
- https://github.com/raml2html/raml2obj/issues/36
- https://github.com/raml2html/raml2obj/issues/27
- https://github.com/raml2html/raml2obj/issues/21
- https://github.com/raml2html/raml2obj/issues/15
- https://github.com/raml2html/raml2html/issues/328
- https://github.com/raml2html/raml2html/issues/280

Maybe someone could replace all these tickets with one new ticket that sums up all the existing problems?

Then there are problems with union types and array types, and then the big issues should be solved I think. But again, doing https://github.com/raml2html/raml2obj/issues/38 first is probably a good idea.

I'll be available for technical input and code reviews, getting new releases out the door, but other then that I think that new development should come from the community. So if you were thinking about helping out, please do. If you need any help to get started, please feel free to reach out to me personally (or just here in the comments).

**Comment by sichvoge** [comment]
@MichaelIT @psychoo118 hope you guys are doing well? Are you still on this with Kevin? Haven't heard from you in ages :D

**Comment by MichaelIT** [comment]
Sorry for that,I am too busy in a large company project this two months.I will check the issues in this weekend.

**Comment by sichvoge** [comment]
Thanks @MichaelIT.

**Comment by sichvoge** [comment]
@nickburns2006 what about you :) i am chasing all of you, muahahaha :P
