### ISSUE TITLE
raml2html 6 much slower than older versions

### ISSUE THREAD

**Issue by tylercloke** [raml2html/raml2html#345]
Hello! Was looking at updating our our raml docs from 0.8 to 1.0.

On raml 0.8 and raml2html 3.0.1, running raml2html on my not large set of raml docs was a couple seconds tops.

I updated to raml2html 6.2.0 and fixed all raml 0.8 -> 1.0 compilation bugs. Everything worked, but raml2html was taking about 3.5 minutes on my docs set!

I then downgraded raml2html to 4.1.1 (the latest 4 release since 4 or later is required for raml 1.0), and raml2html on my docs takes about 2.5 minutes.

I understand that newer versions of raml2html are doing cool things like actually validating your example json, etc so taking a bit longer is expected, but a few second on 3.latest -> 2.5 minutes on 4.latest -> 3.5 minutes on 6.latest really cuts into cycle time on the docs.

Is raml2html taking that long on newer versions expected or is something wrong?

**Comment by kevinrenskers** [comment]
Hi! Well, raml2html doesn't do the actual parsing so the problem probably lies with raml-js-parser-2. It would be good if you could give us your raml documents so we can pinpoint the exact cause, before we point fingers :)

**Comment by tylercloke** [comment]
Hah pointing fingers isn't the point :) Was just wondering if it was expected behavior. I'm going to email you a tarball of our docs at the address in your profile since the API docs are not open-source yet.

**Comment by kevinrenskers** [comment]
Haha no but I was already doing the pointing. Thanks, I'll take a look tonight.

**Comment by kevinrenskers** [comment]
It's not expected no.

**Comment by tylercloke** [comment]
Email sent. Thanks for being responsive!

**Comment by kevinrenskers** [comment]
I parsed your docs directly with raml-1-parser 1.1.19, same version raml2obj uses. Test script:

```
const raml = require('raml-1-parser');

console.time('Parsing RAML');

raml.loadApi('delivery-api.yml', { rejectOnErrors: true }).then(result => {
  console.timeEnd('Parsing RAML')
});
```

Output:

```
Parsing RAML: 169823.763ms
```

Almost 3 minutes, so that is pretty scary. That's before datatype-expansion, raml2obj and raml2html need to do their thing and add some even more time to it (datatype-expansion can also be pretty slow so I am not surprised that you're hitting 3.5 minutes).

I would suggest that you open an issue on https://github.com/raml-org/raml-js-parser-2 (don't mind the `raml-js-parser-2` vs `raml-1-parser naming`, it's horrible but yes the same thing).

**Comment by kevinrenskers** [comment]
Wow wait a sec, if I turn off `{ rejectOnErrors: true }` then parsing is done in 0.1 seconds. That leaves us with the question: do we turn off validation to make raml2html fast again? I mean it should still be fixed in `raml-1-parser` of course but maybe in the meantime we just turn it off?

But then, how many people do depend on that validation you know?

**Comment by kevinrenskers** [comment]
With validation turned off, the whole raml2html process for your docs takes about 50 seconds. Most of that is still from `raml-1-parser`, namely [this step](https://github.com/raml2html/raml2obj/blob/master/index.js#L153):

```
if (result.expand) {
  return result.expand(true).toJSON({ serializeMetadata: false });
}
```

At this moment there is no easy way for me to bring that down. Still, 50 seconds instead of 3.5 minutes is a good first step? :)

**Comment by kevinrenskers** [comment]
Almost 3 minutes:

```
raml.loadApi('delivery-api.yml', { rejectOnErrors: true })
```

0.1 seconds:

```
raml.loadApi('delivery-api.yml')
```

50 seconds:

```
raml.loadApi('delivery-api.yml').then(result => {
  result.expand(true).toJSON({ serializeMetadata: false });
});
```

Their brand new `load` method which does the `expand` and `toJSON` steps behind the scenes:

```
raml.load('delivery-api.yml')
```

....50 seconds.

**Comment by kevinrenskers** [comment]
I created https://github.com/raml-org/raml-js-parser-2/issues/729. I think I'll turn off validation for now, but it's still not going to be fast for your docs I'm afraid.

**Comment by tylercloke** [comment]
What is it validating? The raml or the example json against the schemas?

**Comment by tylercloke** [comment]
Also, might be worth exposing at a CLI option. I could see wanting to iterate on the docs without that validation and then when I build the docs, running the validator.

**Comment by kevinrenskers** [comment]
I think it always parses the RAML itself, but with that option it also tries to validate all examples and stuff. Not sure, not really well documented.

**Comment by kevinrenskers** [comment]
I've released a new version of raml2obj with validation turned off by default. Your document then renders in about 50 seconds.

I'll also release a new version of raml2html later with a new command line option for this.

**Comment by tylercloke** [comment]
Thanks so much!

**Comment by kevinrenskers** [comment]
And done, raml2html 6.3.0 is published. Closing this for now, since I don't see any improvements I can make here in raml2html or raml2obj.

**Comment by kevinrenskers** [comment]
Just keep your eye on https://github.com/raml-org/raml-js-parser-2/issues/729, they'll probably want your RAML files as well :)

**Comment by sichvoge** [comment]
Yes, validation is not only syntax but semantics as well. For running the validation, the parser needs to expand the different trees into a single.

**Comment by kevinrenskers** [comment]
@tylercloke the raml-js-parser guys have made some improvements to the parser. I have released a new version of raml2obj that uses the new parser, and your document now renders in about 6 seconds. Quite a big improvement!

**Comment by tylercloke** [comment]
@kevinrenskers That's fantastic! Thanks. Lmk when you ship with the updated parser.

**Comment by kevinrenskers** [comment]
"I have released a new version of raml2obj that uses the new parser" :)

A simple npm update should do the trick.

**Comment by cebor** [comment]
@kevinrenskers the new v6.3.0 does not validate examples against schemas, is there a way to bring it back?
