### ISSUE TITLE
Raml 0.8 dependencies

### ISSUE THREAD

**Issue by lukiano** [raml2html/raml2html#371]
Just curious if there are plans to update the dependencies of raml2html 3.x, because of security vulnerabilities

**Comment by kevinrenskers** [comment]
Can you be more specific? Which dependencies and vulnerabilities? Since it’s a local command line tool I’m not really sure what security problems could be going on.

**Comment by lukiano** [comment]
For instance, `marked 0.3.6` has a XSS vulnerability. We are using it as a library to convert raml 0.8 to html in our node server.

**Comment by kevinrenskers** [comment]
Marked 0.3.6 is still the latest version available, but in any case, since raml2html depends on marked 0.3.x, we don't need to release an update when they do (assuming they keep it in the 0.3.x range).

But still, assuming you control the RAML that's being converted to a static HTML file, I don't see the big security impact for raml2html?

In general I don't think old versions of raml2html will get updates, no. Sorry, but this is largely a one-man show and I don't have the time to keep multiple versions updated. Only the latest version will get updates when needed.
